# Generated by Django 4.0.3 on 2022-04-01 16:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorimodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='isim', unique=True),
        ),
    ]
