# Generated by Django 4.0.3 on 2022-04-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_yazilarmodeli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazilarmodeli',
            old_name='düzenlenme_tarihi',
            new_name='duzenlenme_tarihi',
        ),
    ]
