# Generated by Django 4.0.3 on 2022-04-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_düzenlenme_tarihi_yazilarmodeli_duzenlenme_tarihi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yazilarmodeli',
            name='icerik',
        ),
    ]
