from .iletisim import iletisim
from .detay import DetayView
from .anasayfa import anasayfa
from .kategori import KategoriListView
from .yazilarım import yazilarim
from .yazi_ekle import YaziEkleCreateView
from .yazi_guncelle import YaziGuncelleUpdateView
from .yazi_sil import YaziSilDeleteView
from .yorum_sil import yorum_sil