from .iletisim import iletisim
from .detay import detay
from .anasayfa import anasayfa
from .kategori import kategori
from .yazilarım import yazilarim
from .yazi_ekle import yazi_ekle
from .yazi_guncelle import yazi_guncelle
from .yazi_sil import yazi_sil
from .yorum_sil import yorum_sil